-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 16:11:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema recruitment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recruitment` ;

-- -----------------------------------------------------
-- Schema recruitment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recruitment` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `recruitment` ;

-- -----------------------------------------------------
-- Table `recruitment`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`roles` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`roles` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `name_vi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`users` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_role` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `loginName_UNIQUE` (`login_name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_roles_idx` (`id_role` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`id_role`)
    REFERENCES `recruitment`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`applicants` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`applicants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `main_cv` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicants_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_applicants_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `recruitment`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`employment_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`employment_types` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`employment_types` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`experiences` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`experiences` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`majors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`majors` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`majors` (
  `id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`positions` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`positions` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`provinces` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`provinces` (
  `id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`recruiters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`recruiters` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`recruiters` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `company_name` VARCHAR(100) NOT NULL,
  `company_phone` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `loginName_UNIQUE` (`id_user` ASC),
  CONSTRAINT `fk_recruiters_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `recruitment`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`jobs` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`jobs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_recruiter` INT(11) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `requirement` VARCHAR(1000) NOT NULL,
  `rights` VARCHAR(1000) NOT NULL,
  `created_date` DATE NULL DEFAULT NULL,
  `expiry_date` DATE NOT NULL,
  `amount` TINYINT(3) NOT NULL,
  `id_experience` TINYINT(1) NOT NULL,
  `id_position` TINYINT(1) NOT NULL,
  `from_salary` INT(11) NOT NULL,
  `to_salary` INT(11) NOT NULL,
  `id_employment_type` TINYINT(1) NOT NULL,
  `id_province` TINYINT(3) NOT NULL,
  `id_major` TINYINT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobs_recruiters_idx` (`id_recruiter` ASC),
  INDEX `fk_jobs_experiences_idx` (`id_experience` ASC),
  INDEX `fk_jobs_levels_idx` (`id_position` ASC),
  INDEX `fk_jobs_majors_idx` (`id_major` ASC),
  INDEX `fk_jobs_employment_types_idx` (`id_employment_type` ASC),
  INDEX `fk_jobs_locations_idx` (`id_province` ASC),
  CONSTRAINT `fk_jobs_employment_types`
    FOREIGN KEY (`id_employment_type`)
    REFERENCES `recruitment`.`employment_types` (`id`),
  CONSTRAINT `fk_jobs_experiences`
    FOREIGN KEY (`id_experience`)
    REFERENCES `recruitment`.`experiences` (`id`),
  CONSTRAINT `fk_jobs_majors`
    FOREIGN KEY (`id_major`)
    REFERENCES `recruitment`.`majors` (`id`),
  CONSTRAINT `fk_jobs_positions`
    FOREIGN KEY (`id_position`)
    REFERENCES `recruitment`.`positions` (`id`),
  CONSTRAINT `fk_jobs_provinces`
    FOREIGN KEY (`id_province`)
    REFERENCES `recruitment`.`provinces` (`id`),
  CONSTRAINT `fk_jobs_recruiters`
    FOREIGN KEY (`id_recruiter`)
    REFERENCES `recruitment`.`recruiters` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`applications` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`applications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_applicant` INT(11) NOT NULL,
  `id_job` INT(11) NOT NULL,
  `register_date` DATE NULL DEFAULT NULL,
  `cv` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applications_applicants_idx` (`id_applicant` ASC),
  INDEX `fk_applications_jobs_idx` (`id_job` ASC),
  CONSTRAINT `fk_applications_applicants`
    FOREIGN KEY (`id_applicant`)
    REFERENCES `recruitment`.`applicants` (`id`),
  CONSTRAINT `fk_applications_jobs`
    FOREIGN KEY (`id_job`)
    REFERENCES `recruitment`.`jobs` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `recruitment`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recruitment`.`districts` ;

CREATE TABLE IF NOT EXISTS `recruitment`.`districts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_province` TINYINT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_districts_province_idx` (`id_province` ASC),
  CONSTRAINT `fk_districts_province`
    FOREIGN KEY (`id_province`)
    REFERENCES `recruitment`.`provinces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
